/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package dfs;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void testAppHasAGreeting() {
        Dfs classUnderTest = new Dfs();
        assertNotNull("app should have a greeting", classUnderTest);
    }
}
