/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package binsearchtree;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    // sarebbe bello farli li test ma non c'ho voglia
}
